config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
                 registrations: 'users/registrations'
                  }
  get 'users/:id', to: 'profiles#show', as: 'user_show'
  root to: 'welcomes#index'

  resources :events do
    resources :invitations
    get 'invitations/:id/accept', to: 'invitations#accept', as: 'accept_invite'
    get 'invitations/:id/decline', to: 'invitations#decline', as: 'decline_invite'
  end



  # post '/events/:id', to: 'invitations/create', as: :create_invitations
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :invitations, dependent: :delete_all
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_events, only: %i[show edit update destroy]

  def index
    @events = Event.all.order(id: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to event_path(@event)
    end
  end

  def show
    @invitations = @event.invitations
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event)
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'SİLİNDİ'
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :limit)
  end

  def set_events
    @event = Event.find(params[:id])
  end
end

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :description %>
  <%= f.text_field :location %>
  <%= f.date_field :date, prefix: DateTime.now.to_date%>
  <%= f.number_field :limit %>
  <%= f.submit "Oluştur"%>
<% end %>

app/views/events/index.html.erb
<div class="container-fluid">
  <div class="row">
    <br><br>
    <% @events.each do |event| %>
        <div class="col-md-4">
          <div class="card-box project-box">
            <h4 class="mt-0 mb-3"><a href="" class="text-dark">
              <a href="<%= event_path event %>">
              <%= event.title %>
              </a>
            </a></h4>
            <p class="text-muted font-13">
              <%= event.description %>
            </p>

            <ul class="list-inline">
              <li class="list-inline-item">
                <h3 class="mb-0"><%= event.date %></h3>
                <p class="text-muted">Tarih</p>
              </li>
              <li class="list-inline-item">
                <h3 class="mb-0"><%= event.limit %></h3>
                <p class="text-muted">Limit</p>
              </li>
            </ul>

            <div class="project-members mb-4">
              <label class="mr-3">Katılımcılar :</label>

              <div style="display: inline-table;margin-bottom: 31px;">
                <%= event.invitations.accepted.count == 0 ? 'henüz bir katılımcı yok' : '' %>
              </div>
              <% event.invitations.accepted.each do |invitation| %>
                  <a href="<%= user_show_path invitation.user %>" data-toggle="tooltip" data-placement="top" title="<%= invitation.user.name_surname %>">
                    <img src="https://pixelmator-pro.s3.amazonaws.com/community/avatar_empty@2x.png" style="border-radius: 100%" class="rounded-circle thumb-sm" alt="friend">
                  </a>
              <% end %>


            </div>

            <label class="">Kontenjan yüzdesi: <span class="text-custom"> <%= event.limit %> / <%= event.invitations.accepted.count %></span></label>
            <div class="progress mb-1" style="height: 7px;">
              <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: <%= (event.invitations.accepted.count.to_f / event.limit.to_f) * 100 %>%;">
              </div><!-- /.progress-bar .progress-bar-danger -->
            </div><!-- /.progress .no-rounded -->
          </div>
        </div><!-- end col-->
    <% end %>

  </div>
  <!-- end row -->

</div>

app/views/events/new.html.erb
<div class="row">
  <br><br>
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="card-box">
      <h4 class="m-t-0 m-b-30 header-title">Yeni Etkinlik Oluştur</h4>

      <%= form_for @event do |f| %>

        <div class="form-group">
          <label for="exampleInputEmail1">Başlık</label>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Etkinlik başlığını giriniz' %>
          <small id="emailHelp" class="form-text text-muted">Etkinlik başlığınızı ilgi çekici şekilde oluşturun.</small>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">Açıklama</label>
          <%= f.text_area :description, class: 'form-control', placeholder: 'Etkinlik içeriğini giriniz' %>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">Etkinlik Adresi</label>
          <%= f.text_field :location, class: 'form-control', placeholder: 'Etkinlik adresini giriniz' %>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">Etkinlik Tarihi</label>
          <%= f.date_field :date, prefix: DateTime.now.to_date, class: 'form-control' %>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">Katılımcı Sayısı</label>
          <%= f.number_field :limit, class: 'form-control' %>
        </div>
          <%= f.submit "Oluştur", class: 'btn btn-primary' %>

      <% end %>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/events/show.html.erb
<br>
<br>
<div class="container">
  <div class="card-box task-detail">
    <div class="media mt-0 m-b-30">
      <img class="d-flex mr-3 rounded-circle" alt="64x64" src="https://avatars.io/twitter/e2d3m" style="width: 48px; height: 48px;float: left; margin-right: 20px;">
      <div class="media-body">
        <h5 class="media-heading mb-0 mt-0"><%= @event.user.email %></h5>
        <span class="badge badge-success">Etkinlik Düzenliyici</span>
      </div>
    </div>

    <h4 class="m-b-20"><%= @event.title %></h4>

    <p class="text-muted">
      <%= @event.description %>
    </p>

    <ul class="list-inline task-dates m-b-0 mt-5">
      <li>
        <h5 class="m-b-5">Etkinlik Adresi</h5>
        <p> <%= @event.location %> </p>
      </li>
      <li>
        <h5 class="m-b-5">Etkinlik Tarihi</h5>
        <p> <%= @event.date %> </p>
      </li>

    </ul>
    <div class="clearfix"></div>

    <div class="assign-team mt-4">
      <h5 class="m-b-5">Katılımcılar</h5>
      <div>
        <div style="display: inline-table;margin-bottom: 31px;">
          <%= @event.invitations.accepted.count == 0 ? 'henüz bir katılımcı yok' : '' %>
        </div>
        <% @event.invitations.accepted.each do |invitation| %>
            <a href="#" data-toggle="tooltip" data-placement="top" title="<%= invitation.user.name_surname %>">
              <img src="https://pixelmator-pro.s3.amazonaws.com/community/avatar_empty@2x.png" style="border-radius: 100%" class="rounded-circle thumb-sm" alt="friend">
            </a>
        <% end %>
      </div>
    </div>

    <div class="attached-files mt-4">
      <div class="row">
        <div class="col-sm-12">
          <div class="text-right m-t-30">
            <% if @current_user.present? && @event.user == @current_user %>
              <%= link_to 'Sil', @event, method: :delete, class: 'btn btn-danger waves-effect', data: { confirm: 'emin misin?' } %>
            <% end %>
            <% if @event.user != @current_user %>
              <% if @current_user && !@current_user.invitations.where(event_id: @event.id).first %>
                <%= link_to 'Baş Vur', event_invitations_path(@event), class: 'btn btn-success waves-effect', method: :post %>
              <% else %>
                <%= link_to 'İptal Et', event_invitation_path(@event), class: 'btn btn-danger waves-effect', method: :delete, data: { confirm: 'EMİNMİSİNNN ???' } %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>


<div class="container">
  <div class="card-box">
    <h4 class="header-title m-t-0 m-b-30">Gelen Katılımcı İstekleri</h4>

    <ul class="nav nav-tabs tabs-bordered">
      <li class="nav-item">
        <a href="#home-b1" data-toggle="tab" aria-expanded="false" class="nav-link active show">
          <i class="fi-monitor mr-2"></i> Onay Bekleyenler
        </a>
      </li>
      <li class="nav-item">
        <a href="#profile-b1" data-toggle="tab" aria-expanded="true" class="nav-link">
          <i class="fi-head mr-2"></i> Katılanlar
        </a>
      </li>
      <li class="nav-item">
        <a href="#messages-b1" data-toggle="tab" aria-expanded="false" class="nav-link">
          <i class="fi-mail mr-2"></i> İptal Edilenler
        </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane" id="home-b1">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>id</th>
            <th>Ad Soyad</th>
            <th>Mail Adresi</th>
            <th>İşlem</th>
          </tr>
          </thead>
          <tbody>

          <% @invitations.waiting.each do |inv| %>
              <tr>
                <th scope="row"><%= inv.user.id %></th>
                <td><%= inv.user.name_surname %></td>
                <td><%= inv.user.email %></td>
                <td>
                  <% if @current_user == @event.user %>
                      <%= link_to 'Onayla', event_accept_invite_path(@event, inv), class: 'btn btn-success' %>
                      <%= link_to 'İptal Et', event_decline_invite_path(@event, inv), class: 'btn btn-danger' %>
                  <% else %>
                      <button class="btn- btn-warning">onay bekliyor</button>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <%= @invitations.waiting.count == 0 ? 'hiç kullanıcı yok' : '' %>
      </div>
      <div class="tab-pane" id="profile-b1">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>id</th>
            <th>Ad Soyad</th>
            <th>Mail Adresi</th>
            <th>İşlem</th>
          </tr>
          </thead>
          <tbody>
          <% @invitations.accepted.each do |inv| %>
              <tr>
                <th scope="row"><%= inv.user.id %></th>
                <td><%= inv.user.name_surname %></td>
                <td><%= inv.user.email %></td>
                <td>
                  <% if @current_user == @event.user %>
                      <%= link_to 'İptal Et', event_decline_invite_path(@event, inv), class: 'btn btn-danger' %>
                  <% else %>
                      <button class="btn- btn-success">onaylanmış katılımcı</button>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <%= @invitations.accepted.count == 0 ? 'hiç kullanıcı yok' : '' %>
      </div>
      <div class="tab-pane" id="messages-b1">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>id</th>
            <th>Ad Soyad</th>
            <th>Mail Adresi</th>
            <th>İşlem</th>
          </tr>
          </thead>
          <tbody>

          <% @invitations.declined.each do |inv| %>
              <tr>
                <th scope="row"><%= inv.user.id %></th>
                <td><%= inv.user.name_surname %></td>
                <td><%= inv.user.email %></td>
                <td>
                  <% if @current_user == @event.user %>
                      <%= link_to 'Onayla', event_accept_invite_path(@event, inv), class: 'btn btn-success' %>
                  <% else %>
                    <button class="btn- btn-warning">onay bekliyor</button>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <%= @invitations.declined.count == 0 ? 'hiç kullanıcı yok' : '' %>
      </div>
    </div>
  </div>
</div>