config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
                 registrations: 'users/registrations'
                  }
  get 'users/:id', to: 'profiles#show', as: 'user_show'
  root to: 'welcomes#index'

  resources :events do
    resources :invitations
    get 'invitations/:id/accept', to: 'invitations#accept', as: 'accept_invite'
    get 'invitations/:id/decline', to: 'invitations#decline', as: 'decline_invite'
  end



  # post '/events/:id', to: 'invitations/create', as: :create_invitations
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kimgelio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <style>
      .menu
      {
        background-color: #3498db;
        width: 100%;
        height: auto;
        padding: 10px 10px;
        margin: 0px;
        z-index: 1;
        opacity: 0.9;
      }

      .menu  .navbar-nav > .active > a
      {
        background-color : #04A3ED;
        color: white;
        font-weight: bold;
      }

      .menu  .navbar-nav >  li >  a
      {
        font-size: 13px;
        color: white;
        padding: 10px 20px;

      }
      .menu  .navbar-nav >  li >  a:hover
      {
        background-color: #04A3ED;
      }

      .navbar-header > a
      {
        font-family: 'Ubuntu Condensed', sans-serif;
        margin: 0px;
        text-decoration: none;
        color: white;
        font-size: 25px;
        padding: 5px 30px;
      }
      .navbar-header > a:hover
      {
        text-decoration: none;
        color: #04A3ED;
      }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="/">KimGelio</a>
      </div>
      <div>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= root_path %>">Anasayfa</a></li>
          <li><a href="<%= events_path %>">Etkinlikler</a></li>

          <% if @current_user.present? %>
              <li style="background: #2ecc71;"><a href="<%= new_event_path %>">Etkinlik oluştur</a></li>
              <li style="background: #54abe2;"><%= link_to 'Çıkış', destroy_user_session_path, method: :delete %></li>
              <li style="background: #54abe2;">
                <%= link_to user_show_path(@current_user) do%>
                  <i class="fa fa-plus"></i>
                  <%= @current_user.present? ? "#{@current_user.name_surname}" : 'hoşgeldin ziyaretçi' %>
                <% end %>
              </li>

        <% else %>
              <li><a href="<%= new_user_registration_path %>" ><span class="glyphicon glyphicon-user"></span> Kayıt Ol</a></li>
              <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Giriş Yap</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</html>